<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PetType;
use App\Models\Breed;

class DogBreedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Find the pet type for dogs
        $dogType = PetType::where('name', 'dog')->first();

        if (!$dogType) {
            echo "Dog pet type not found. Make sure to run PetTypeSeeder first.\n";
            return;
        }

        $breeds = [
            "Afador",
            "Affenhuahua",
            "Affenpinscher",
            "Afghan Hound",
            "Airedale Terrier",
            "Akbash",
            "Akita",
            "Akita Chow",
            "Akita Pit",
            "Akita Shepherd",
            "Alaskan Klee Kai",
            "Alaskan Malamute",
            "American Bulldog",
            "American English Coonhound",
            "American Eskimo",
            "American Eskimo Dog",
            "American Foxhound",
            "American Hairless Terrier",
            "American Leopard Hound",
            "American Pit Bull Terrier",
            "American Pugabull",
            "American Staffordshire Terrier",
            "American Water Spaniel",
            "Anatolian Shepherd",
            "Anatolian Shepherd Dog",
            "Appenzeller Sennenhunde",
            "Argentine Dogo",
            "Auggie",
            "Aussiedoodle",
            "Aussiepom",
            "Australian Cattle Dog",
            "Australian Kelpie",
            "Australian Retriever",
            "Australian Shepherd",
            "Australian Shepherd Husky",
            "Australian Shepherd Lab Mix",
            "Australian Shepherd Pit Bull Mix",
            "Australian Stumpy Tail Cattle Dog",
            "Australian Terrier",
            "Azawakh",
            "Barbet",
            "Basenji",
            "Bassador",
            "Basset Fauve de Bretagne",
            "Basset Hound",
            "Basset Retriever",
            "Bavarian Mountain Scent Hound",
            "Beabull",
            "Beagle",
            "Beaglier",
            "Bearded Collie",
            "Beauceron",
            "Bedlington Terrier",
            "Belgian Malinois",
            "Belgian Sheepdog",
            "Belgian Tervuren",
            "Bergamasco Sheepdog",
            "Berger Picard",
            "Bernedoodle",
            "Bernese Mountain Dog",
            "Bichon Frise",
            "Biewer Terrier",
            "Black Mouth Cur",
            "Black Russian Terrier",
            "Black and Tan Coonhound",
            "Bloodhound",
            "Blue Lacy",
            "Bluetick Coonhound",
            "BoShih",
            "Bocker",
            "Boerboel",
            "Boglen Terrier",
            "Bohemian Shepherd",
            "Bolognese",
            "Borador",
            "Border Collie",
            "Border Sheepdog",
            "Border Terrier",
            "Bordoodle",
            "Borzoi",
            "Bossie",
            "Boston Boxer",
            "Boston Terrier",
            "Boston Terrier Pekingese Mix",
            "Bouvier des Flandres",
            "Boxador",
            "Boxer",
            "Boxerdoodle",
            "Boxmatian",
            "Boxweiler",
            "Boykin Spaniel",
            "Bracco Italiano",
            "Braque du Bourbonnais",
            "Briard",
            "Brittany",
            "Broholmer",
            "Brussels Griffon",
            "Bugg",
            "Bull Arab",
            "Bull Terrier",
            "Bull-Pei",
            "Bullador",
            "Bullboxer Pit",
            "Bulldog",
            "Bullmastiff",
            "Bullmatian",
            "Cairn Terrier",
            "Canaan Dog",
            "Cane Corso",
            "Cardigan Welsh Corgi",
            "Carolina Dog",
            "Catahoula Bulldog",
            "Catahoula Leopard Dog",
            "Caucasian Shepherd Dog",
            "Cav-a-Jack",
            "Cavachon",
            "Cavador",
            "Cavalier King Charles Spaniel",
            "Cavapoo",
            "Central Asian Shepherd Dog",
            "Cesky Terrier",
            "Chabrador",
            "Cheagle",
            "Chesapeake Bay Retriever",
            "Chi Chi",
            "Chi-Poo",
            "Chigi",
            "Chihuahua",
            "Chilier",
            "Chinese Crested",
            "Chinese Crested Dog",
            "Chinese Shar-Pei",
            "Chinook",
            "Chion",
            "Chipin",
            "Chiweenie",
            "Chorkie",
            "Chow Chow",
            "Chow Shepherd",
            "Chug",
            "Chusky",
            "Cirneco dell’Etna",
            "Clumber Spaniel",
            "Cockalier",
            "Cockapoo",
            "Cocker Spaniel",
            "Collie",
            "Collie (Rough and Smooth)",
            "Corgi Inu",
            "Corgidor",
            "Corman Shepherd",
            "Coton de Tulear",
            "Croatian Sheepdog",
            "Curly-Coated Retriever",
            "Dachsador",
            "Dachshund - Long Hair",
            "Dachshund - Smooth",
            "Dachshund - Wire",
            "Dalmatian",
            "Dandie Dinmont Terrier",
            "Daniff",
            "Danish-Swedish Farmdog",
            "Deutscher Wachtelhund",
            "Doberdor",
            "Doberman Pinscher",
            "Docker",
            "Dogo Argentino",
            "Dogue de Bordeaux",
            "Doodle",
            "Dorgi",
            "Dorkie",
            "Doxiepoo",
            "Doxle",
            "Drentsche Patrijshond",
            "Drever",
            "Dutch Shepherd",
            "English Bulldog",
            "English Cocker Spaniel",
            "English Foxhound",
            "English Setter",
            "English Springer Spaniel",
            "English Toy Spaniel",
            "Entlebucher Mountain",
            "Entlebucher Mountain Dog",
            "Estrela Mountain Dog",
            "Eurasier",
            "Field Spaniel",
            "Fila Brasileiro",
            "Finnish Lapphund",
            "Finnish Spitz",
            "Flat-Coated Retriever",
            "Fox Terrier",
            "Fox Terrier (Smooth)",
            "Fox Terrier (Wire)",
            "French Bulldog",
            "French Bullhuahua",
            "French Spaniel",
            "Frenchton",
            "Frengle",
            "German Longhaired Pointer",
            "German Pinscher",
            "German Shepherd Dog",
            "German Shepherd Pit Bull",
            "German Shepherd Rottweiler Mix",
            "German Sheprador",
            "German Shorthaired Pointer",
            "German Spitz",
            "German Wirehaired Pointer",
            "Giant Schnauzer",
            "Glen of Imaal Terrier",
            "Goberian",
            "Goldador",
            "Golden Cocker Retriever",
            "Golden Mountain Dog",
            "Golden Retriever",
            "Golden Retriever Corgi",
            "Golden Shepherd",
            "Goldendoodle",
            "Gollie",
            "Gordon Setter",
            "Great Dane",
            "Great Pyrenees",
            "Great Pyrenees",
            "Greater Swiss Mountain Dog",
            "Greyador",
            "Greyhound",
            "Hamiltonstovare",
            "Hanoverian Scenthound",
            "Harrier",
            "Havanese",
            "Hokkaido",
            "Horgi",
            "Hovawart",
            "Huskita",
            "Husky",
            "Huskydoodle",
            "Ibizan Hound",
            "Icelandic Sheepdog",
            "Irish Red & White Setter",
            "Irish Red And White Setter",
            "Irish Setter",
            "Irish Terrier",
            "Irish Water Spaniel",
            "Irish Wolfhound",
            "Italian Greyhound",
            "Jack Chi",
            "Jack Russell Terrier",
            "Jack-A-Poo",
            "Jackshund",
            "Japanese Chin",
            "Japanese Spitz",
            "Kai Ken",
            "Karelian Bear Dog",
            "Keeshond",
            "Kerry Blue Terrier",
            "King Shepherd",
            "Kishu Ken",
            "Komondor",
            "Kooikerhondje",
            "Korean Jindo Dog",
            "Kuvasz",
            "Kyi-Leo",
            "Lab Pointer",
            "Labernese",
            "Labmaraner",
            "Labrabull",
            "Labradane",
            "Labradoodle",
            "Labrador Retriever",
            "Labrastaff",
            "Labsky",
            "Lagotto Romagnolo",
            "Lakeland Terrier",
            "Lancashire Heeler",
            "Leonberger",
            "Lhasa Apso",
            "Lhasapoo",
            "Lowchen",
            "Löwchen",
            "Maltese",
            "Maltese Shih Tzu",
            "Maltipoo",
            "Manchester Terrier",
            "Manchester Terrier (Toy)",
            "Maremma Sheepdog",
            "Mastador",
            "Mastiff",
            "Mini Australian Shepherd",
            "Miniature Bull Terrier",
            "Miniature Pinscher",
            "Miniature Poodle",
            "Miniature Schnauzer",
            "Mixed",
            "Morkie",
            "Mountain Cur",
            "Mudi",
            "Mutt (Mixed)",
            "Neapolitan Mastiff",
            "Newfoundland",
            "Norfolk Terrier",
            "North American Shepherd",
            "Northern Inuit Dog",
            "Norwegian Buhund",
            "Norwegian Elkhound",
            "Norwegian Lundehund",
            "Norwich Terrier",
            "Not Defined",
            "Nova Scotia Duck Tolling Retriever",
            "Old English Sheepdog",
            "Other",
            "Otterhound",
            "Papillon",
            "Papipoo",
            "Parson Russell Terrier",
            "Patterdale Terrier",
            "Peekapoo",
            "Pekingese",
            "Pembroke Welsh Corgi",
            "Petit Basset Griffon Vendeen",
            "Petit Basset Griffon Vendéen",
            "Pharaoh Hound",
            "Pitsky",
            "Plott",
            "Pocket Beagle",
            "Pointer",
            "Polish Lowland Sheepdog",
            "Pomapoo",
            "Pomchi",
            "Pomeagle",
            "Pomeranian",
            "Pomsky",
            "Poochon",
            "Poodle",
            "Poodle (Toy)",
            "Poodle Mix",
            "Portuguese Podengo Pequeno",
            "Portuguese Pointer",
            "Portuguese Sheepdog",
            "Portuguese Water Dog",
            "Presa Canario",
            "Pug",
            "Pugalier",
            "Puggle",
            "Puginese",
            "Puli",
            "Pyredoodle",
            "Pyrenean Mastiff",
            "Pyrenean Shepherd",
            "Rat Terrier",
            "Redbone Coonhound",
            "Rhodesian Ridgeback",
            "Rottador",
            "Rottle",
            "Rottweiler",
            "Russell Terrier",
            "Saint Berdoodle",
            "Saint Bernard",
            "Saluki",
            "Samoyed",
            "Samusky",
            "Schipperke",
            "Schnauzer (Standard)",
            "Schnoodle",
            "Scottish Deerhound",
            "Scottish Terrier",
            "Sealyham Terrier",
            "Sheepadoodle",
            "Shepsky",
            "Shetland Sheepdog",
            "Shiba Inu",
            "Shichon",
            "Shih Tzu",
            "Shih-Poo",
            "Shiloh Shepherd",
            "Shiranian",
            "Shollie",
            "Shorkie",
            "Siberian Husky",
            "Silken Windhound",
            "Silky Terrier",
            "Skye Terrier",
            "Sloughi",
            "Small Munsterlander Pointer",
            "Soft Coated Wheaten Terrier",
            "Spanish Mastiff",
            "Spanish Water Dog",
            "Spinone Italiano",
            "Springador",
            "Stabyhoun",
            "Staffordshire Bull Terrier",
            "Staffy Bull Bullmastiff",
            "Standard Poodle",
            "Standard Schnauzer",
            "Sussex Spaniel",
            "Swedish Lapphund",
            "Swedish Vallhund",
            "Taiwan Dog",
            "Terripoo",
            "Texas Heeler",
            "Tibetan Mastiff",
            "Tibetan Spaniel",
            "Tibetan Terrier",
            "Tosa",
            "Toy Fox Terrier",
            "Transylvanian Hound",
            "Treeing Tennessee Brindle",
            "Treeing Walker Coonhound",
            "Unknown",
            "Valley Bulldog",
            "Vizsla",
            "Weimaraner",
            "Welsh Springer Spaniel",
            "Welsh Terrier",
            "West Highland White Terrier",
            "Westiepoo",
            "Whippet",
            "Whoodle",
            "Wirehaired Pointing Griffon",
            "Xoloitzcuintli",
            "Yorkipoo",
            "Yorkshire Terrier"
        ];

        foreach ($breeds as $breedName) {
            Breed::create([
                'name' => $breedName,
                'pet_type_id' => $dogType->id
            ]);
        }
    }
}
